<a href="https://colab.research.google.com/github/vi-xoxo/DIF62130_B_25_2311533010/blob/main/Praktikum4/GaussianNaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

dataset_dict = {
    'Rainfall': [0.0, 2.0, 7.0, 18.0, 3.0, 3.0, 0.0, 1.0, 0.0, 25.0, 0.0, 18.0, 9.0, 5.0, 0.0, 1.0, 7.0, 0.0, 0.0, 7.0, 5.0, 3.0, 0.0, 2.0, 0.0, 8.0, 4.0, 4.0],
    'Temperature': [29.4, 26.7, 28.3, 21.1, 20.0, 18.3, 17.8, 22.2, 20.6, 23.9, 23.9, 22.2, 27.2, 21.7, 27.2, 23.3, 24.4, 25.6, 27.8, 19.4, 29.4, 22.8, 31.1, 25.0, 26.1, 26.7, 18.9, 28.9],
    'Humidity': [85.0, 90.0, 78.0, 96.0, 80.0, 70.0, 65.0, 95.0, 70.0, 80.0, 70.0, 90.0, 75.0, 80.0, 88.0, 92.0, 85.0, 75.0, 92.0, 90.0, 85.0, 88.0, 65.0, 70.0, 60.0, 95.0, 70.0, 78.0],
    'WindSpeed': [2.1, 21.2, 1.5, 3.3, 2.0, 17.4, 14.9, 6.9, 2.7, 1.6, 30.3, 10.9, 3.0, 7.5, 10.3, 3.0, 3.9, 21.9, 2.6, 17.3, 9.6, 1.9, 16.0, 4.6, 3.2, 8.3, 3.2, 2.2],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(dataset_dict)
df.head()


Rainfall  Temperature  Humidity  WindSpeed Play
0       0.0         29.4      85.0        2.1   No
1       2.0         26.7      90.0       21.2   No
2       7.0         28.3      78.0        1.5  Yes
3      18.0         21.1      96.0        3.3  Yes
4       3.0         20.0      80.0        2.0  Yes

Bagi data menjadi data latih dan data uji

In [2]:
# set feaature matrix x and target vector y
X, y = df.drop(columns='Play'), df['Play']

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, shuffle=False)
print(pd.concat([X_train, y_train], axis=1), end='\n\n')
print(pd.concat([X_test, y_test], axis=1))

   Rainfall  Temperature  Humidity  WindSpeed Play
0       0.0         29.4      85.0        2.1   No
1       2.0         26.7      90.0       21.2   No
2       7.0         28.3      78.0        1.5  Yes
3      18.0         21.1      96.0        3.3  Yes
4       3.0         20.0      80.0        2.0  Yes
5       3.0         18.3      70.0       17.4   No
6       0.0         17.8      65.0       14.9  Yes
7       1.0         22.2      95.0        6.9   No

    Rainfall  Temperature  Humidity  WindSpeed Play
8        0.0         20.6      70.0        2.7  Yes
9       25.0         23.9      80.0        1.6  Yes
10       0.0         23.9      70.0       30.3  Yes
11      18.0         22.2      90.0       10.9  Yes
12       9.0         27.2      75.0        3.0  Yes
13       5.0         21.7      80.0        7.5   No
14       0.0         27.2      88.0       10.3   No
15       1.0         23.3      92.0        3.0  Yes
16       7.0         24.4      85.0        3.9  Yes
17       0.0        


Transforming non-gaussian distributed data

In [3]:
from sklearn.preprocessing import PowerTransformer

#initialize and fit the powertransformer
pt = PowerTransformer(standardize=True) #standard scaling already included
X_train_transformed = pt.fit_transform(X_train)
X_test_transformed = pt.transform(X_test)
print(X_train_transformed)

[[-1.37646656  1.37618286  0.19677805 -0.95913026]
 [-0.01511993  0.93407309  0.70416661  1.33152919]
 [ 0.97036275  1.20547044 -0.46911885 -1.27477416]
 [ 1.69186129 -0.30935667  1.3477664  -0.50668166]
 [ 0.29435138 -0.62773866 -0.28417065 -1.00628701]
 [ 0.29435138 -1.18780617 -1.16623265  1.15324306]
 [-1.37646656 -1.37092388 -1.56706492  1.00939638]
 [-0.48287375 -0.01990101  1.237876    0.25270446]]


Training Steps

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.preprocessing import PowerTransformer

dataset_dict = {
    'Rainfall': [0.0, 2.0, 7.0, 18.0, 3.0, 3.0, 0.0, 1.0, 0.0, 25.0, 0.0, 18.0, 9.0, 5.0, 0.0, 1.0, 7.0, 0.0, 0.0, 7.0, 5.0, 3.0, 0.0, 2.0, 0.0, 8.0, 4.0, 4.0],
    'Temperature': [29.4, 26.7, 28.3, 21.1, 20.0, 18.3, 17.8, 22.2, 20.6, 23.9, 23.9, 22.2, 27.2, 21.7, 27.2, 23.3, 24.4, 25.6, 27.8, 19.4, 29.4, 22.8, 31.1, 25.0, 26.1, 26.7, 18.9, 28.9],
    'Humidity': [85.0, 90.0, 78.0, 96.0, 80.0, 70.0, 65.0, 95.0, 70.0, 80.0, 70.0, 90.0, 75.0, 80.0, 88.0, 92.0, 85.0, 75.0, 92.0, 90.0, 85.0, 88.0, 65.0, 70.0, 60.0, 95.0, 70.0, 78.0],
    'WindSpeed': [2.1, 21.2, 1.5, 3.3, 2.0, 17.4, 14.9, 6.9, 2.7, 1.6, 30.3, 10.9, 3.0, 7.5, 10.3, 3.0, 3.9, 21.9, 2.6, 17.3, 9.6, 1.9, 16.0, 4.6, 3.2, 8.3, 3.2, 2.2],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(dataset_dict)

# Replace 'Yes' with 1 and 'No' with 0 in the 'Play' column
df['Play'] = df['Play'].replace({'Yes': 1, 'No': 0})

x, y = df.drop(columns=['Play']), df['Play']
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, shuffle=False)
print(pd.concat([x_train, y_train], axis=1), end='\n\n')
print(pd.concat([x_test, y_test], axis=1))

pt = PowerTransformer(standardize=True)

x_train_transformed = pt.fit_transform(x_train)
x_test_transformed = pt.transform(x_test)
print(x_train_transformed, end='\n\n')
x_test_transformed

    Rainfall  Temperature  Humidity  WindSpeed  Play
0        0.0         29.4      85.0        2.1     0
1        2.0         26.7      90.0       21.2     0
2        7.0         28.3      78.0        1.5     1
3       18.0         21.1      96.0        3.3     1
4        3.0         20.0      80.0        2.0     1
5        3.0         18.3      70.0       17.4     0
6        0.0         17.8      65.0       14.9     1
7        1.0         22.2      95.0        6.9     0
8        0.0         20.6      70.0        2.7     1
9       25.0         23.9      80.0        1.6     1
10       0.0         23.9      70.0       30.3     1
11      18.0         22.2      90.0       10.9     1
12       9.0         27.2      75.0        3.0     1
13       5.0         21.7      80.0        7.5     0
14       0.0         27.2      88.0       10.3     0
15       1.0         23.3      92.0        3.0     1
16       7.0         24.4      85.0        3.9     1
17       0.0         25.6      75.0       21.9

/tmp/ipython-input-4-2048582033.py:18: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Play'] = df['Play'].replace({'Yes': 1, 'No': 0})


array([[ 0.86716996, -1.30821327,  0.88230332,  1.18049877],
       [ 0.64971568,  1.70170305,  0.31329077,  0.64344897],
       [ 0.31508602, -0.29618045,  0.6525535 , -1.18113717],
       [-1.12664679,  2.22253179, -1.77644441,  1.11436724],
       [ 0.05597219,  0.36522078, -1.28303046, -0.1431076 ],
       [-1.12664679,  0.6976956 , -2.24947872, -0.56515379],
       [ 0.95173556,  0.87952169,  1.46898652,  0.49733804],
       [ 0.50348308, -1.45591451, -1.28303046, -0.56515379],
       [ 0.50348308,  1.54897227, -0.45277799, -1.00886221]])

In [5]:
# Calculate prior probabilities for each class
prior_probabilities = y_train.value_counts(normalize=True)
prior_probabilities

Play
1    0.578947
0    0.421053
Name: proportion, dtype: float64

In [6]:
def Calculate_class_probabilities(x_train_transformed, y_train, features_names):
    classes = y_train.unique()
    equations = pd.DataFrame(index=classes, columns=features_name)

    for cls in classes:
      x_class = x_train_transformed[y_train == cls]
      mean= x_class.mean(axis=0)
      std = x_class.std(axis=0)